obj-$(CONFIG_SENSORS_YAS529_MAGNETIC)	+= yas_mag_kernel_driver.o
obj-$(CONFIG_SENSORS_BMA023_ACCEL)	+= yas_acc_kernel_driver_ariesve.o
obj-$(CONFIG_SENSORS_ORIENTATION)	+= yas_ori_kernel_driver.o
obj-$(CONFIG_OPTICAL_GP2A)		+= gp2a_proximity_ariesve.o gp2a_rpc.o gp2a_light.o
 

