obj-$(CONFIG_SENSORS_YAS529_MAGNETIC)	+= yas_mag_kernel_driver.o
obj-$(CONFIG_SENSORS_BMA222_ACCEL)	+= yas_acc_kernel_driver.o
obj-$(CONFIG_SENSORS_ORIENTATION)	+= yas_ori_kernel_driver.o
obj-$(CONFIG_OPTICAL_GP2A)		+= gp2a_proximity.o gp2a_rpc.o gp2a_light.o
