##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: Varun Mahajan <m.varun@samsung.com>
##############################################################################
# VERSION&DATE	: Version 0.1
##############################################################################

obj-$(CONFIG_SAMSUNG_FM_SI4709) += Si4709_main.o
obj-$(CONFIG_SAMSUNG_FM_SI4709) += Si4709_dev.o
obj-$(CONFIG_SAMSUNG_FM_SI4709) += Si4709_i2c_drv.o



